project:
  type: website
  output-dir: docs/

website:
  title: Python Setup and Usage
  page-navigation: true
  reader-mode: true

  repo-url: https://github.com/chendaniely/python_setup
  repo-actions: [edit, issue]

  sidebar:
    style: "floating"
    search: true
    contents:

      - section: "The Whole Game"
        contents:
          - href: 110-the_whole_game.qmd
            text: Example Data Science Project

      - section: "Install Python"
        contents:
          - href: 210-python_install.qmd
            text: Pyenv

      - section: "Use Python"
        contents:
          - href: 310-python_versions.qmd
            text: Python Versions
          - href: 320-python_virtual_environments.qmd
            text: Virtual Environments
          - href: 330-ide.qmd
            text: IDE Setup

      # - section: "Reference"
      #   contents:
      #     - href: 410-pyenv_usage.qmd
      #       text: pyenv

      # - section: "Extras"
      #   contents:
      #     - href: 510-pyenv_virtualenv.qmd
      #       text: "pyenv-virtualenv"
      #     - href: 520-pipenv.qmd
      #       text: "pipenv"
      #     - href: 530-pipx.qmd
      #       text: "pipx"

      # - section: "Appendix"
      #   contents:
      #     - href: 610-additional_resources.qmd
      #       text: Additional Resources
      #     - href: 690-concept_maps.qmd
      #       text: Concept Maps

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: Contents
    toc-expand: true

    number-sections: true
    number-depth: 4
    anchor-sections: true
    smooth-scroll: true

    code-tools:
      source: true
      toggle: true
      caption: none
    #code-line-numbers: true
    code-copy: true
    code-link: true

editor:
  render-on-save: true

filters:
   - include-code-files
